### ISSUE TITLE
request

### ISSUE THREAD

**Issue by pizzav-xyz** [neelmaster101/Neels-Discord#1]
can you make a version without the dark?

**Comment by ItsRecharge** [comment]
Could you please elaborate on your comment? Are you looking for a light-mode theme?

**Comment by pizzav-xyz** [comment]
> Could you please elaborate on your comment? Are you looking for a light-mode theme?

i want the theme without the darkenedness

**Comment by ItsRecharge** [comment]
Do you mean light-mode?

**Comment by pizzav-xyz** [comment]
> Do you mean light-mode?

no

**Comment by pizzav-xyz** [comment]
> Do you mean light-mode?

i want normal dark mode not the super dark

**Comment by ItsRecharge** [comment]
if you copy the contents of `Neel's-Discord.theme.css` then paste in the QuickCSS section in themes, then you can edit all colors by changing the values. Everything is labeled and you just have to change the number to your personal preference.

**Comment by pizzav-xyz** [comment]
> if you copy the contents of `Neel's-Discord.theme.css` then paste in the QuickCSS section in themes, then you can edit all colors by changing the values. Everything is labeled and you just have to change the number to your personal preference.

how do i  just get the default dark mode?

**Comment by ItsRecharge** [comment]
Remove the link to raw url/file from your client

**Comment by pizzav-xyz** [comment]
> 



> Remove the link to raw url/file from your client



> Remove the link to raw url/file from your client

then i dont have the with rounded chat and sidebars
and the settings icons

**Comment by ItsRecharge** [comment]
Ok, I understand the issue. I’m heading out for now, but I’ll get back to you in about an hour.

**Comment by pizzav-xyz** [comment]
> Ok, I understand the issue. I’m heading out for now, but I’ll get back to you in about an hour.

it has been 2 hours

**Comment by ItsRecharge** [comment]
Use this url: https://raw.githubusercontent.com/ItsRecharge/Neels-Discord/main/NoDark.theme.css
 
 I made some edits only to keep the rounded edges and icons and stuff like that, have fun

**Comment by pizzav-xyz** [comment]
> 

thanks

**Comment by pizzav-xyz** [comment]
> Use this url: https://raw.githubusercontent.com/ItsRecharge/Neels-Discord/main/NoDark.theme.css
> 
> I made some edits only to keep the rounded edges and icons and stuff like that, have fun
@ItsRecharge 
how to use on replugged?

**Comment by ItsRecharge** [comment]
go to settings and under themes there should be a place where you can paste a link

**Comment by pizzav-xyz** [comment]
> 

isnt there on replugged

> go to settings and under themes there should be a place where you can paste a link

**Comment by ItsRecharge** [comment]
what does it say then?

**Comment by pizzav-xyz** [comment]
> what does it say then?

![image](https://github.com/ItsRecharge/Neels-Discord/assets/103120356/9cf9dd90-4ab4-48ba-98ad-176fe4594ec6)

**Comment by pizzav-xyz** [comment]
> go to settings and under themes there should be a place where you can paste a link

ok, found out how to do it but it seems like it still changes colors

**Comment by pizzav-xyz** [comment]
> > go to settings and under themes there should be a place where you can paste a link
> 
> ok, found out how to do it but it seems like it still changes colors

for example the accent collor

**Comment by ItsRecharge** [comment]
Could you send a screenshot of what you did and the outcome?

**Comment by pizzav-xyz** [comment]
> go to settings and under themes there should be a place where you can paste a link

![image](https://github.com/ItsRecharge/Neels-Discord/assets/103120356/eb385233-d25b-472a-abb4-dbd857ead8ab)
color change 
![image](https://github.com/ItsRecharge/Neels-Discord/assets/103120356/c7b2f458-21e9-40d0-a422-50795dbfd888)
color change  
![image](https://github.com/ItsRecharge/Neels-Discord/assets/103120356/b1b21a26-0d0f-4668-bae6-7be4e48748d4)

**Comment by ItsRecharge** [comment]
im working on it

**Comment by pizzav-xyz** [comment]
> im working on it

actually i kinda like it, could you change it to be hsl(40, 100%, 50%)
You can send here or in discord I asked if you were itsrecharged

**Comment by ItsRecharge** [comment]
bruh...

well i already did it :https://raw.githubusercontent.com/ItsRecharge/Neels-Discord/main/NoDark.theme.css

**Comment by pizzav-xyz** [comment]
> bruh...
> 
> well i already did it :https://raw.githubusercontent.com/ItsRecharge/Neels-Discord/main/NoDark.theme.css
> 

https://github.com/ItsRecharge/Neels-Discord/commit/838454dabec0d79f4da53d49827646cc8944c30c

**Comment by ItsRecharge** [comment]
Nice, have a good time
